version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc0
    environment:
      - EULA=TRUE
      - VERSION=1.20.4
      - TYPE=PAPER
      - ONLINE_MODE=FALSE
    ports:
      - "25565:25565"
    volumes:
      - ./server-icon.png:/data/server-icon.png
    restart: unless-stopped
